# system configs for reframe testing
systems:

  - name: workstation
    descr: GFDL workstations
    hostnames:
      - ldt-[0-9]*.gfdl.noaa.gov
    modules_system: lmod
    partitions:
      - name: ws
        descr: run locally with mpirun
        scheduler: local
        launcher: mpirun
        environs:
          - spack-intel-oneapi
          - spack-gnu-mpich
          - spack-gnu-openmpi
          - spack-gnu-vortex-tracker
          - spack-intel-vortex-tracker

  - name: analysis
    descr: GFDL Analysis Cluster
    hostnames:
      - ldt-[0-9]*.gfdl.noaa.gov
    modules_system: lmod
    partitions:
      - name: ws
        descr: run locally with mpirun
        scheduler: slurm
        launcher: srun
        environs:
          - spack-intel-oneapi
          - spack-gnu-mpich
          - spack-gnu-openmpi
          - spack-gnu-vortex-tracker
          - spack-intel-vortex-tracker

  - name: lscamd50-d
    descr: MSD development machine
    hostnames:
      - lscamd50-d.gfdl.noaa.gov
    modules_system: lmod
    partitions:
      - name: amd
        descr: run locally with mpirun
        scheduler: local
        launcher: mpirun
        environs:
          - intel-oneapi

  - name: gaea
    descr: gaea
    hostnames:
      - gaea*
    modules_system: lmod
    partitions:
      - name: batch
        descr: c5 batch partition
        scheduler: slurm
        launcher: srun
        environs:
          - cray-intel-oneapi-prod
          - cray-intel-oneapi-debug
          - cray-gnu
        sched_options:
          slurm_multi_cluster_mode:
            - c5

environments:
# this is using the intel oneapi modulefiles directly from intel, mainly for lscamd50-d
  - name: intel-oneapi
    modules:
      - oneapi
      - compiler
      - mpi
      - netcdf
      - libyaml
    ftn: mpiifx
    cc: mpiicx
# these are using the spack package names instead
  - name: spack-intel-oneapi
    modules:
      - intel-oneapi-compilers
      - intel-oneapi-mpi
      - netcdf-c
      - netcdf-fortran
      - autoconf
      - automake
      - libtool
    ftn: mpiifx
    cc: mpiicx
  - name: spack-gnu-mpich
    modules:
      - gcc
      - mpich
      - netcdf-c
      - netcdf-fortran
      - autoconf
      - automake
      - libtool
    ftn: mpifort
    cc: mpicc
  - name: spack-gnu-openmpi
    modules:
      - gcc
      - openmpi
      - netcdf-c
      - netcdf-fortran
      - autoconf
      - automake
      - libtool
    ftn: mpifort
    cc: mpicc
# these are also spack package names, but with some additions for the vortex tracker
  - name: spack-gnu-vortex-tracker
    modules:
      - gcc
      - netcdf-c
      - netcdf-fortran
      - cmake
      - libpng/1.6.47
      - jasper/4.2.4
      - zlib/1.3.1
      - zlib-ng/2.2.4
      - g2c/2.1.0
      - g2/4.0.0
      - g2tmpl/1.14.0
      - bacio/2.6.0
      - w3emc/2.12.0
      - nco/5.3.3
      - cdo/2.5.2
      - wgrib2/3.6.0
      - grib-util/1.5.0
    ftn: gfortran
    cc: gcc
  - name: spack-intel-vortex-tracker
    modules:
      - intel-oneapi-compilers
      - intel-oneapi-mpi # the netcdf cmake module searches for mpi if built with it, but the vortex tracker doesn't actually use it
      - netcdf-c
      - netcdf-fortran
      - cmake
      - libpng/1.6.47
      - jasper/4.2.4
      - zlib/1.3.1
      - zlib-ng/2.2.4
      - g2c/2.1.0
      - g2/4.0.0
      - g2tmpl/1.14.0
      - bacio/2.6.0
      - w3emc/2.12.0
      - nco/5.3.3
      - cdo/2.5.2
      - wgrib2/3.6.0
      - grib-util/1.5.0
    ftn: ifx
    cc: icx
# the rest are cray-specific module names/PrgEnv's
  - name: cray-intel-oneapi-prod
    modules:
      - PrgEnv-intel/8.6.0
      - intel-oneapi
      - cray-hdf5
      - cray-netcdf
    cflags:
      - -O2 -debug minimal -sox -traceback -march=core-avx-i
    fflags:
      - -O3 -debug minimal -fp-model source -march=core-avx-i

  - name: cray-intel-oneapi-debug
    modules:
      - PrgEnv-intel/8.6.0
      - intel-oneapi
      - cray-hdf5
      - cray-netcdf
    cflags:
      - -O0 -g -march=core-avx-i
    fflags:
      - -g -O0 -check -check noarg_temp_created -check nopointer -check nouninit -warn -warn noerrors -fpe0 -ftrapuv -march=core-avx-i
  - name: cray-gnu
    modules:
      - PrgEnv-gnu/8.6.0
      - gcc-native
      - cray-hdf5
      - cray-netcdf
