# system configs for reframe testing
systems:

  - name: workstation
    descr: GFDL workstations
    hostnames:
      - ldt-[0-9]*.gfdl.noaa.gov
    modules_system: lmod
    partitions:
      - name: ws
        descr: run locally with mpirun
        scheduler: local
        launcher: mpirun
        environs:
          - spack-intel-oneapi
          - spack-gnu-mpich
          - spack-gnu-openmpi

  - name: analysis
    descr: GFDL Analysis Cluster
    hostnames:
      - ldt-[0-9]*.gfdl.noaa.gov
    modules_system: lmod
    partitions:
      - name: ws
        descr: run locally with mpirun
        scheduler: slurm
        launcher: srun
        environs:
          - spack-intel-oneapi
          - spack-gnu-mpich
          - spack-gnu-openmpi

  - name: lscamd50-d
    descr: MSD development machine
    hostnames:
      - lscamd50-d.gfdl.noaa.gov
    modules_system: lmod
    partitions:
      - name: amd
        descr: run locally with mpirun
        scheduler: local
        launcher: mpirun
        environs:
          - intel-oneapi
          - spack-gnu-mpich
          - spack-gnu-openmpi

  - name: gaea
    descr: gaea
    hostnames:
      - gaea*
    modules_system: lmod
    partitions:
      - name: batch
        descr: c5 partition
        scheduler: slurm
        launcher: srun
        environs:
          - cray-intel-oneapi-prod
          - cray-intel-oneapi-debug
          - cray-gnu
        sched_options:
          slurm_multi_cluster_mode:
            - c5

# these environments load the minimum to compile fms, not necessarily needed for all tests but most gfdl code relies on mpi/netcdf anyway
# tests can also load specific modules, but its better to keep modules here so that tests can be run anywhere without system-specific module names
environments:
# this is using the intel oneapi modulefiles directly from intel, mainly for lscamd50-d
  - name: intel-oneapi
    modules:
      - oneapi
      - compiler
      - mpi
      - netcdf
      - libyaml
    ftn: mpiifx
    cc: mpiicx
# these are using the spack package names instead
  - name: spack-intel-oneapi
    modules:
      - intel-oneapi-compilers
      - intel-oneapi-mpi
      - netcdf-c
      - netcdf-fortran
      - autoconf
      - automake
      - libtool
    ftn: mpiifx
    cc: mpiicx
  - name: spack-gnu-mpich
    modules:
      - gcc
      - mpich
      - netcdf-c
      - netcdf-fortran
      - autoconf
      - automake
      - libtool
    ftn: mpifort
    cc: mpicc
  - name: spack-gnu-openmpi
    modules:
      - gcc
      - openmpi
      - netcdf-c
      - netcdf-fortran
      - autoconf
      - automake
      - libtool
    ftn: mpifort
    cc: mpicc
# the rest are cray-specific module names/PrgEnv's
  - name: cray-intel-oneapi-prod
    modules:
      - PrgEnv-intel/8.6.0
      - intel-oneapi
      - cray-hdf5
      - cray-netcdf
    cflags:
      - -O2 -debug minimal -sox -traceback -march=core-avx-i
    fflags:
      - -O3 -debug minimal -fp-model source -march=core-avx-i

  - name: cray-intel-oneapi-debug
    modules:
      - PrgEnv-intel/8.6.0
      - intel-oneapi
      - cray-hdf5
      - cray-netcdf
    cflags:
      - -O0 -g -march=core-avx-i
    fflags:
      - -g -O0 -check -check noarg_temp_created -check nopointer -check nouninit -warn -warn noerrors -fpe0 -ftrapuv -march=core-avx-i
  - name: cray-gnu
    modules:
      - PrgEnv-gnu/8.6.0
      - gcc-native
      - cray-hdf5
      - cray-netcdf
